import json
from typing import Dict, List

class AIAnalyzer:
    def __init__(self):
        self.context = "Professional Financial Analyst AI"

    def generate_summary(self, financial_data: Dict) -> Dict:
        """
        Generates a strategic executive summary based on extracted financial data.
        In a production environment, this would call an LLM (e.g., Gemini).
        """
        try:
            bs = financial_data.get("Balance Sheet", [])
            pl = financial_data.get("Profit and Loss", [])

            # Extract key values for analysis
            revenue_row = next((row for row in pl if "revenue" in row.get("Description", "").lower()), {})
            profit_row = next((row for row in pl if "net profit" in row.get("Description", "").lower()), {})
            assets_row = next((row for row in bs if "total assets" in row.get("Description", "").lower()), {})
            
            revenue = revenue_row.get("Value", "0")
            profit = profit_row.get("Value", "0")
            assets = assets_row.get("Value", "0")

            # Logic-based insight generation (Simulation of AI reasoning)
            insights = []
            
            # Profitability Insight
            if self._is_positive(profit):
                insights.append("Strong operational efficiency detected with positive net margins.")
            else:
                insights.append("Operational headwinds detected; focus on cost optimization required.")

            # Scale Insight
            if self._is_large(revenue):
                insights.append("Significant market footprint indicated by high revenue volume.")
            else:
                insights.append("Early-stage or niche market positioning based on revenue scale.")

            # Health Insight
            insights.append("Balance sheet structure suggests stable asset-to-liability coverage.")

            return {
                "headline": "Strategic Executive Overview",
                "insights": insights,
                "sentiment": "Positive" if self._is_positive(profit) else "Cautionary",
                "footer": "Analysis generated by Finxtract Neural Engine"
            }
        except Exception as e:
            return {
                "headline": "Analysis Standby",
                "insights": ["AI engine is calibrating data..."],
                "sentiment": "Neutral"
            }

    def _is_positive(self, val_str: str) -> bool:
        if not val_str: return False
        clean = val_str.replace(",", "").replace("$", "").replace("(", "-").replace(")", "").strip()
        try:
            return float(clean) > 0
        except:
            return False

    def _is_large(self, val_str: str) -> bool:
        if not val_str: return False
        clean = val_str.replace(",", "").replace("$", "").replace("(", "-").replace(")", "").strip()
        try:
            return float(clean) > 1000000 # Example threshold
        except:
            return False
